### ISSUE TITLE
./bin/kafkagosaur.wasm not found

### ISSUE THREAD

**Issue by 7flash** [arjun-1/kafkagosaur#19]
```
error: Uncaught NotFound: No such file or directory (os error 2): readfile './bin/kafkagosaur.wasm'
  const wasmBytes = await Deno.readFile(wasmFilePath);
                    ^
    at async Object.readFile (ext:deno_fs/30_fs.js:693:18)
    at async runGoWasm (https://deno.land/x/kafkagosaur@v0.0.6/mod.ts:45:21)
```

```
import KafkaGoSaur from "https://deno.land/x/kafkagosaur@v0.0.6/mod.ts";

const broker = await kafkaGoSaur.createWriter({
  topic: "book-updates",
  address: "localhost:9092",
});
```

**Comment by 7flash** [comment]
Fixed by manually copying kafkagosaur.wasm from this repository into bin folder relative to my app root

**Comment by 7flash** [comment]
But then it throws an error:

```
error: Uncaught CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 0a 0a 0a 0a @+0
  const instiatedSource = await WebAssembly.instantiate(
                                            ^
    at runGoWasm (https://deno.land/x/kafkagosaur@v0.0.6/mod.ts:46:45)
```
